# Generated by Django 4.1.3 on 2022-11-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_harness_user_helmets_user_instruments_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harness',
            name='user',
        ),
    ]
