# Generated by Django 4.1.3 on 2022-11-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_harness_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harness',
            name='user',
        ),
        migrations.RemoveField(
            model_name='helmets',
            name='user',
        ),
        migrations.RemoveField(
            model_name='instruments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reserves',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wings',
            name='user',
        ),
    ]
