# Generated by Django 4.1.3 on 2022-12-03 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0011_harness_user_helmets_user_instruments_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
