# Generated by Django 4.1.3 on 2022-11-11 10:53

import django.core.validators
from django.db import migrations, models
import paragliding_shop.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(3), paragliding_shop.accounts.validators.validate_only_alphanumeric]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(3), paragliding_shop.accounts.validators.validate_only_alphanumeric]),
        ),
    ]
