# Generated by Django 4.1.3 on 2022-11-30 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='order',
            field=models.FloatField(default='1', validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
