# Generated by Django 4.1.3 on 2022-11-30 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_appuser_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='order',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5.0)]),
        ),
    ]
