# Generated by Django 4.1.3 on 2022-11-30 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_appuser_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='order',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
