# Generated by Django 4.1.3 on 2022-12-04 16:30

from django.db import migrations, models
import paragliding_shop.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_appuser_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[paragliding_shop.accounts.validators.MaxFileSizeInMbValidator(1.5)]),
        ),
    ]
